version: '3'
services:
  mysql:
    image: mysql:5.7.21
    command: [
        'mysqld',
        '--innodb-buffer-pool-size=20M',
        '--character-set-server=utf8',
        '--collation-server=utf8_general_ci',
        '--default-time-zone=+8:00',
        '--lower-case-table-names=1',
        '--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
    ]
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
      - "MYSQL_ROOT_PASSWORD="
      - "MYSQL_DATABASE=micro_mall"
    ports:
      - "3306:3306"
    restart: always
  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins
    restart: always
    user: root
#    network_mode: "host"    #网络模式（默认bridge）
    ports:
      - "9000:8080"
      - "9001:5000"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - '/Volumes/jenkins:/var/jenkins_home'
